groups:
  - name: lokan-platform
    interval: 1m
    rules:
      - alert: LokanHighErrorRate
        expr: |
          (
            sum by (service, env)(rate(lokan_http_requests_total{status=~"5.."}[5m]))
            /
            sum by (service, env)(rate(lokan_http_requests_total[5m]))
          ) > 0.02
        for: 5m
        labels:
          severity: page
          team: lokan-platform
        annotations:
          summary: "High HTTP error rate"
          description: |
            5xx errors exceed 2% of total requests for the last 5 minutes in {{ $labels.service }} (env {{ $labels.env }}).
      - alert: LokanLatencySLOBreach
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, service, env)(rate(lokan_http_request_duration_seconds_bucket[5m]))
          ) > 0.75
        for: 10m
        labels:
          severity: page
          team: lokan-platform
        annotations:
          summary: "p95 latency above 750ms"
          description: |
            p95 latency for {{ $labels.service }} in {{ $labels.env }} has exceeded 750ms for the last 10 minutes.
      - alert: LokanMetricsScrapeMissing
        expr: up{job=~"lokan-.*"} == 0
        for: 5m
        labels:
          severity: ticket
          team: lokan-observability
        annotations:
          summary: "Prometheus scrape missing"
          description: |
            Prometheus scrape target {{ $labels.job }} (env {{ $labels.env }}) has been down or missing for 5 minutes.
