openapi: 3.1.0
info:
  title: LokanOS Audit Log Service
  version: 0.1.0
  description: Immutable event logging pipeline for compliance scenarios.
servers:
  - url: https://audit-log.lokanos.local
    description: Internal service mesh endpoint.
tags:
  - name: Diagnostics
    description: Common diagnostic endpoints across LokanOS services.
  - name: Audit Log
    description: Endpoints for retrieving compliance audit trails.
components:
  securitySchemes:
    mtls:
      type: mutualTLS
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
          required:
            - code
            - message
      required:
        - error
    HealthStatus:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    DiagnosticInfo:
      type: object
      properties:
        uptimeSeconds:
          type: integer
          format: int64
        details:
          type: object
          additionalProperties: true
          nullable: true
      required:
        - uptimeSeconds
  responses:
    ErrorResponse:
      description: Structured error payload.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
paths:
  /audit-log/health:
    get:
      operationId: AuditLogHealth
      summary: Audit log service health probe.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Service is healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          $ref: '#/components/responses/ErrorResponse'
  /audit-log/metrics:
    get:
      operationId: AuditLogMetrics
      summary: Prometheus metrics exposition.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Prometheus metrics payload.
          content:
            text/plain:
              schema:
                type: string
  /audit-log/diag:
    get:
      operationId: AuditLogDiagnostics
      summary: Diagnostic snapshot for troubleshooting.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Runtime diagnostic information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagnosticInfo'
  /audit-log/entries:
    get:
      operationId: AuditLogListEntries
      summary: Retrieve recent audit log entries.
      tags:
        - Audit Log
      security:
        - mtls: []
      responses:
        '200':
          description: Audit log entries ordered from newest to oldest.
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                required:
                  - entries
        '401':
          $ref: '#/components/responses/ErrorResponse'
