openapi: 3.1.0
info:
  title: LokanOS Radio Coordinator
  version: 0.1.0
  description: Manages RF channel assignments and interference mitigation.
servers:
  - url: https://radio-coord.lokanos.local
    description: Internal service mesh endpoint.
tags:
  - name: Diagnostics
    description: Common diagnostic endpoints across LokanOS services.
  - name: Radio Coordinator
    description: Wireless spectrum coordination APIs.
components:
  securitySchemes:
    mtls:
      type: mutualTLS
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
          required:
            - code
            - message
      required:
        - error
    HealthStatus:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    DiagnosticInfo:
      type: object
      properties:
        uptimeSeconds:
          type: integer
          format: int64
        details:
          type: object
          additionalProperties: true
          nullable: true
      required:
        - uptimeSeconds
  responses:
    ErrorResponse:
      description: Structured error payload.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
paths:
  /radio-coord/health:
    get:
      operationId: RadioCoordinatorHealth
      summary: Radio coordinator health probe.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Service is healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          $ref: '#/components/responses/ErrorResponse'
  /radio-coord/metrics:
    get:
      operationId: RadioCoordinatorMetrics
      summary: Prometheus metrics exposition.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Prometheus metrics payload.
          content:
            text/plain:
              schema:
                type: string
  /radio-coord/diag:
    get:
      operationId: RadioCoordinatorDiagnostics
      summary: Diagnostic snapshot for troubleshooting.
      tags:
        - Diagnostics
      responses:
        '200':
          description: Runtime diagnostic information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagnosticInfo'
  /radio-coord/channels:
    get:
      operationId: RadioCoordinatorListChannels
      summary: Inspect allocated RF channels.
      tags:
        - Radio Coordinator
      security:
        - mtls: []
      responses:
        '200':
          description: Current radio channel assignments.
          content:
            application/json:
              schema:
                type: object
                properties:
                  assignments:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                required:
                  - assignments
        '401':
          $ref: '#/components/responses/ErrorResponse'
