version: "3.9"
services:
  updater:
    image: rust:1.73-bullseye
    working_dir: /workspace
    volumes:
      - ..:/workspace
    command: >-
      bash -lc "apt-get update && apt-get install -y curl && cargo run --bin updater"
    environment:
      RUST_LOG: info
    ports:
      - "8006:8006"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://127.0.0.1:8006/health"]
      interval: 5s
      timeout: 2s
      retries: 12
