x-rust-env: &rust-env
  LOG_LEVEL: debug
  RUST_BACKTRACE: "1"
  RUST_LOG: info

x-workspace-volume: &workspace-volume
  - ..:/workspace

x-rust-service: &rust-service
  image: rust:1.73-bullseye
  working_dir: /workspace
  environment:
    <<: *rust-env
  volumes: *workspace-volume
  tty: true

services:
  nats:
    image: nats:2.10.12-alpine
    profiles: ["core", "full"]
    command:
      - -js
      - --http_port
      - "8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "4222"]
      interval: 5s
      timeout: 2s
      retries: 12

  postgres:
    image: postgres:15-alpine
    profiles: ["full"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device_registry
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d device_registry"]
      interval: 5s
      timeout: 2s
      retries: 12

  device-registry:
    build:
      context: .
      dockerfile: services/device-registry/Dockerfile
    image: lokan/device-registry:dev
    pull_policy: build
    profiles: ["full"]
    environment:
      RUST_LOG: info
      DEVICE_REGISTRY_DATABASE_URL: "${DEVICE_REGISTRY_DATABASE_URL:-sqlite:///var/lib/device-registry/dev.db}"
    volumes:
      - device-registry-data:/var/lib/device-registry
    ports:
      - "8001:8001"
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/busybox", "wget", "-qO-", "http://127.0.0.1:8001/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  api-gateway:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl openssl;
        rm -rf /var/lib/apt/lists/*;
        if [ ! -f security/pki/dev/out/ca/lokan-dev-root-ca.cert.pem ]; then
          pushd security/pki/dev > /dev/null;
          ./generate_ca.sh;
          ./generate_server_cert.sh api-gateway localhost,api-gateway,api-gateway.local;
          ./generate_client_cert.sh developer-cli;
          popd > /dev/null;
        fi;
        scripts/dev/wait-for.sh nats:4222 60;
        scripts/dev/wait-for.sh device-registry:8001 60;
        scripts/dev/wait-for.sh audit-log:8008 60;
        exec cargo run -p api-gateway;
      "
    environment:
      <<: *rust-env
      API_GATEWAY_ANNOUNCE_MDNS: "false"
      API_GATEWAY_BUS__URL: nats://nats:4222
      API_GATEWAY_DEVICE_REGISTRY_URL: http://device-registry:8001
      API_GATEWAY_AUDIT__ENDPOINT: http://audit-log:8008/v1/events
      API_GATEWAY_TLS__CERT_PATH: security/pki/dev/out/services/api-gateway/api-gateway.cert.pem
      API_GATEWAY_TLS__KEY_PATH: security/pki/dev/out/services/api-gateway/api-gateway.key.pem
      API_GATEWAY_TLS__CLIENT_CA_PATH: security/pki/dev/out/ca/lokan-dev-root-ca.cert.pem
    volumes: *workspace-volume
    ports:
      - "8443:8443"
    depends_on:
      nats:
        condition: service_healthy
      device-registry:
        condition: service_healthy
      audit-log:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl --fail --silent \
            --cert security/pki/dev/out/clients/developer-cli/developer-cli.cert.pem \
            --key security/pki/dev/out/clients/developer-cli/developer-cli.key.pem \
            --cacert security/pki/dev/out/ca/lokan-dev-root-ca.cert.pem \
            https://127.0.0.1:8443/v1/health
      interval: 10s
      timeout: 2s
      retries: 12

  rule-engine:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        exec cargo run -p rule-engine;
      "
    volumes: *workspace-volume
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8002/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  scene-svc:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        scripts/dev/wait-for.sh device-registry:8001 60;
        exec cargo run -p scene-svc;
      "
    environment:
      <<: *rust-env
      DEVICE_REGISTRY_URL: http://device-registry:8001
    volumes: *workspace-volume
    ports:
      - "8003:8003"
    depends_on:
      device-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8003/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  presence-svc:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        exec cargo run -p presence-svc;
      "
    volumes: *workspace-volume
    ports:
      - "8004:8004"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8004/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  energy-svc:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        exec cargo run -p energy-svc;
      "
    volumes: *workspace-volume
    ports:
      - "8005:8005"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8005/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  updater:
    <<: *rust-service
    profiles: ["core", "full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        scripts/dev/wait-for.sh nats:4222 60;
        exec cargo run -p updater;
      "
    environment:
      <<: *rust-env
    volumes:
      - ..:/workspace
      - updater-data:/workspace/data/updater
    ports:
      - "8006:8006"
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8006/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  telemetry-pipe:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        exec cargo run -p telemetry-pipe;
      "
    volumes: *workspace-volume
    ports:
      - "8007:8007"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8007/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  audit-log:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        mkdir -p data/audit-log;
        exec cargo run -p audit-log;
      "
    environment:
      <<: *rust-env
      AUDIT_LOG_PATH: data/audit-log/audit.log
    volumes:
      - ..:/workspace
      - audit-log-data:/workspace/data/audit-log
    ports:
      - "8008:8008"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8008/health"]
      interval: 5s
      timeout: 2s
      retries: 12

  radio-coord:
    <<: *rust-service
    profiles: ["full"]
    command: >-
      bash -lc "
        set -euo pipefail;
        export DEBIAN_FRONTEND=noninteractive;
        apt-get update;
        apt-get install -y --no-install-recommends ca-certificates curl;
        rm -rf /var/lib/apt/lists/*;
        scripts/dev/wait-for.sh nats:4222 60;
        exec cargo run -p radio-coord;
      "
    environment:
      <<: *rust-env
      RADIO_COORD_ANNOUNCE_MDNS: "false"
      RADIO_COORD_BUS__URL: nats://nats:4222
    volumes: *workspace-volume
    ports:
      - "8009:8009"
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://127.0.0.1:8009/v1/health"]
      interval: 5s
      timeout: 2s
      retries: 12

volumes:
  device-registry-data:
  audit-log-data:
  updater-data:
  postgres-data:
