/**
 * This file is auto-generated by tools/oas2ts.ts.
 * Do not edit this file directly.
 */

export type DiagnosticInfo = {
  details?: {
    [key: string]: unknown;
  } | null;
  uptimeSeconds: number;
};

export type ErrorResponse = {
  error: {
    code: string;
    message: string;
  };
};

export type HealthStatus = {
  status: string;
};
