[package]
name = "common-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = []
with-serde = ["serde"]
