roles:
  owner:
    inherits: [admin]
  admin:
    inherits: [member]
  member:
    inherits: [guest]
  guest: {}

routes:
  - pattern: /v1/health
    methods: [GET]
    roles: [guest]
    audit_action: system.health
  - pattern: /v1/info
    methods: [GET]
    roles: [guest]
    audit_action: system.info
  - pattern: /v1/diag/ping
    methods: [GET]
    roles: [admin, owner]
    audit_action: diag.ping
  - pattern: /v1/diag/routes
    methods: [GET]
    roles: [admin, owner]
    audit_action: diag.routes
  - pattern: /v1/devices
    methods: [GET]
    roles: [member, admin, owner]
    audit_action: devices.list
  - pattern: /v1/devices
    methods: [POST]
    roles: [admin, owner]
    audit_action: devices.create
  - pattern: /v1/commissioning/ble/handshake
    methods: [POST]
    roles: [guest, member, admin, owner]
    audit_action: commissioning.handshake
  - pattern: /v1/commissioning/csr
    methods: [POST]
    roles: [guest, member, admin, owner]
    audit_action: commissioning.csr
  - pattern: /v1/commissioning/verify
    methods: [POST]
    roles: [guest, member, admin, owner]
    audit_action: commissioning.verify
