[package]
name = "common-msgbus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = []
json = ["serde"]
