name: API Gateway CI

on:
  push:
    paths:
      - 'services/api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'
  pull_request:
    paths:
      - 'services/api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'

jobs:
  test:
    name: Build and test api-gateway
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api-gateway
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: services/api-gateway/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Run build
        run: npm run build
