name: OpenAPI validation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  oas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Generate bundled OpenAPI specification
        run: make oas
